server:
	port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
      
spring:
	application:
		name: wiki
	data.mongodb:
		host: localhost
		port: 27017
		uri: mongodb://localhost:27017/wikicode
		database: wikicode